name: d3-tojson-format
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'TOJSON_START'
      - run: echo "${{ toJSON(fromJSON('{\"b\":2,\"a\":1}')) }}"
      - run: echo 'TOJSON_END'
