name: d3-tojson-format
on:
  push:
    paths:
      - .github/workflows/d3-tojson-format.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'TOJSON_START'
      - run: echo "${{ toJSON(fromJSON('{\"b\":2,\"a\":1}')) }}"
      - run: echo 'TOJSON_END'
