name: d6-join-object
on:
  push:
    paths:
      - .github/workflows/d6-join-object.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "JOIN_OBJ_RESULT=[${{ join(fromJSON('{"a":1}')) }}]"
