name: Webhook Push Simple
on: push
jobs:
  trigger:
    runs-on: [self-hosted, trigger-e2e]
    steps:
      - name: Log event
        run: |
          echo "EVENT: push"
          echo "REF: ${{ github.ref }}"
