name: Webhook Wiki Pages
on:
  gollum:
  page_build:
jobs:
  trigger:
    runs-on: [self-hosted, trigger-e2e]
    steps:
      - name: Log event
        run: |
          echo "EVENT: ${{ github.event_name }}"
          echo "ACTION: ${{ github.event.action }}"
